### ISSUE TITLE
Add chat command description

### ISSUE THREAD

**Issue by Wuzzy2** [ac-minetest/anticheat#1]
The chat commands are lacking a description, which means that `/help <command>` does not work. Users will have a hard time in figuring out the purpose of the new commands, so can you please add a chat command descriptions for all commands?

Use `/help all` in-game for “inspiration”. ;-)

**Comment by ghost** [comment]
Agreed. And chat commands that are registered do not match chat commands in the README

**Comment by ac-minetest** [comment]
added /help, fixed chat commands in readme
