### ISSUE TITLE
Fly anticheat has false positives

### ISSUE THREAD

**Issue by Wuzzy2** [ac-minetest/anticheat#2]
The fly anticheat mechanism sometimes incorrectly kills players for flying when in fact they were not cheating at all.
I am not sure how to reproduce this but I know it still happens sometimes.
I think you just have to move and jump around quickly (maybe together with sneaking / using sneak elevators).

This is critical when this mod is used together with `boneworld` since each death drains your XP. So perfectly honest players can lose their life and XP for no reason. :-(

**Comment by ac-minetest** [comment]
this only happens if player was caught "in air" 2 times in a row and second time player is higher than first time.  It seems extraordinary difficult to detect when player is "flying" if you want to make it so it wont unnecessarily lag server ( with more than 2 players ) AND to minimize false positives.

It seems easy enough (just look if player is above ground with line of sight perhaps) but in practice this is fail.

Will remove kill to stop xp loss but cheat notice will remain.

**Comment by Wuzzy2** [comment]
Sooo, you are basically saying, the false-positive still remains?
Then the bug is not really fixed IMO. :-(

**Comment by ghost** [comment]
I'm getting players with a false positive. (mostly)
They are using the perfectly valid method of riding down a stream of water into a deep area.

**Comment by Baigle** [comment]
On some popular servers fast mode is granted by default, and using it while jumping on water often causes false positives. This happens more often with the speed boost from crystal boots (ethereal mod) and using fast mode. There are also hackers on clients like dragonfire, or others on app stores that allow placing client side blocks and flying that way, using a 9th slot.

A preemptive check that the player is not standing on a set of standard block heights (including sawtable items from moreblocks mod), and is also not hovering in the air, would prevent false flying alerts when they are jumping down the side of a building, for example. Or that while flying, their movements do not continually line up with client side block placements, alternatively according to the delta offsets between positions.

One solution may be to get the player's velocity and vector along two points close together and seeing if they follow the game's standard physics accelerations. The calculation can even be done on the client and then the server does validity checks every now and again on the data.
